//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAITAPLON.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public int ID { get; set; }
        public string TenSanPham { get; set; }
        public Nullable<decimal> GiaBanMoi { get; set; }
        public Nullable<decimal> GiaBanCu { get; set; }
        public string TomTat { get; set; }
        public string BaiViet { get; set; }
        public Nullable<int> idHang { get; set; }
        public string HinhAnh { get; set; }
    
        public virtual HangSanXuat HangSanXuat { get; set; }
        public virtual CTDonHang CTDonHang { get; set; }
    }
}
